name: WorldListTrashCan
version: '4.0.1'
main: org.worldlisttrashcan.WorldListTrashCan
author: BlueNine QQ 2831508831
api-version: '1.13'
folia-supported: true

commands:
  WorldListTrashCan:
    description: WorldListTrashCan插件主指令
  WTC:
    description: WorldListTrashCan插件副指令
permissions:
  WorldListTrashCan.BanGui:
    description: 将不回收的物品加入，如果重复加入同一物品则是取消不回收该物品
    default: true
  WorldListTrashCan.GlobalTrashOpen:
    description: 打开全球垃圾桶
    default: true
  WorldListTrashCan.help:
    description: 帮助
    default: true
  WorldListTrashCan.GlobalBan:
    description: 全球垃圾桶黑名单gui
    default: false
  WorldListTrashCan.Look:
    description: 点击实体获取实体类型
    default: false
  WorldListTrashCan.DropMode:
    description: 打开禁止丢弃模式
    default: true